// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Calvary.Data
{
    // Configuration
    public partial class Configuration
    {
        public string Key { get; set; } // Key (Primary key)
        public string Value { get; set; } // Value
        public DateTime ChangedWhen { get; set; } // ChangedWhen
        public string ChangedWho { get; set; } // ChangedWho
        
        public Configuration()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
