// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Calvary.Data
{
    public interface ICalvaryContext : IDisposable
    {
        DbSet<BaptizedReason> BaptizedReasons { get; set; } // BaptizedReason
        DbSet<Configuration> Configurations { get; set; } // Configuration
        DbSet<EducationGrade> EducationGrades { get; set; } // EducationGrade
        DbSet<EducationMajor> EducationMajors { get; set; } // EducationMajor
        DbSet<Ethnic> Ethnics { get; set; } // Ethnic
        DbSet<Hobby> Hobbies { get; set; } // Hobby
        DbSet<Income> Incomes { get; set; } // Income
        DbSet<IncomeType> IncomeTypes { get; set; } // IncomeType
        DbSet<Job> Jobs { get; set; } // Job
        DbSet<KlasisMapping> KlasisMappings { get; set; } // KlasisMapping
        DbSet<LookUp> LookUps { get; set; } // LookUp
        DbSet<Meeting> Meetings { get; set; } // Meeting
        DbSet<MeetingType> MeetingTypes { get; set; } // MeetingType
        DbSet<Member> Members { get; set; } // Member
        DbSet<MemberMarriage> MemberMarriages { get; set; } // MemberMarriage
        DbSet<MemberNote> MemberNotes { get; set; } // MemberNote
        DbSet<MemberState> MemberStates { get; set; } // MemberState
        DbSet<MemberStateHistory> MemberStateHistories { get; set; } // MemberStateHistory
        DbSet<MemberVisit> MemberVisits { get; set; } // MemberVisit
        DbSet<Menu> Menus { get; set; } // Menu
        DbSet<MutationType> MutationTypes { get; set; } // MutationType
        DbSet<Region> Regions { get; set; } // Region
        DbSet<ResignReason> ResignReasons { get; set; } // ResignReason
        DbSet<Role> Roles { get; set; } // Role
        DbSet<RoleMenu> RoleMenus { get; set; } // RoleMenu
        DbSet<Schedule> Schedules { get; set; } // Schedule
        DbSet<ScheduleGroup> ScheduleGroups { get; set; } // ScheduleGroup
        DbSet<Shrine> Shrines { get; set; } // Shrine
        DbSet<Skill> Skills { get; set; } // Skill
        DbSet<Sysdiagram> Sysdiagrams { get; set; } // sysdiagrams
        DbSet<UserLogin> UserLogins { get; set; } // UserLogin
        DbSet<VisitResult> VisitResults { get; set; } // VisitResult
        DbSet<Worship> Worships { get; set; } // Worship
        DbSet<WorshipType> WorshipTypes { get; set; } // WorshipType

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(CancellationToken cancellationToken);
    }

}
// </auto-generated>
