// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Calvary.Data
{
    // LookUp
    public partial class LookUpMapping : EntityTypeConfiguration<LookUp>
    {
        public LookUpMapping()
            : this("dbo")
        {
        }
 
        public LookUpMapping(string schema)
        {
            ToTable(schema + ".LookUp");
            HasKey(x => x.Key);

            Property(x => x.Key).HasColumnName("Key").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(20).HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.Values).HasColumnName("Values").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(500);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
