// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Calvary.Data
{
    // Meeting
    public partial class MeetingMapping : EntityTypeConfiguration<Meeting>
    {
        public MeetingMapping()
            : this("dbo")
        {
        }
 
        public MeetingMapping(string schema)
        {
            ToTable(schema + ".Meeting");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName("Id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.MeetingTypeId).HasColumnName("MeetingTypeId").IsRequired().HasColumnType("int");
            Property(x => x.Date).HasColumnName("Date").IsRequired().HasColumnType("date");
            Property(x => x.FromTime).HasColumnName("FromTime").IsOptional().HasColumnType("datetime");
            Property(x => x.ToTime).HasColumnName("ToTime").IsOptional().HasColumnType("datetime");
            Property(x => x.Subject).HasColumnName("Subject").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(200);
            Property(x => x.PengerjaPria).HasColumnName("PengerjaPria").IsRequired().HasColumnType("int");
            Property(x => x.PengerjaWanita).HasColumnName("PengerjaWanita").IsRequired().HasColumnType("int");
            Property(x => x.PenatuaPria).HasColumnName("PenatuaPria").IsRequired().HasColumnType("int");
            Property(x => x.PenatuaWanita).HasColumnName("PenatuaWanita").IsRequired().HasColumnType("int");
            Property(x => x.PartisipanPria).HasColumnName("PartisipanPria").IsRequired().HasColumnType("int");
            Property(x => x.PartisipanWanita).HasColumnName("PartisipanWanita").IsRequired().HasColumnType("int");
            Property(x => x.CreatedWhen).HasColumnName("CreatedWhen").IsRequired().HasColumnType("datetime");
            Property(x => x.CreatedBy).HasColumnName("CreatedBy").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.ChangedWhen).HasColumnName("ChangedWhen").IsRequired().HasColumnType("datetime");
            Property(x => x.ChangedWho).HasColumnName("ChangedWho").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);

            // Foreign keys
            HasRequired(a => a.MeetingType).WithMany(b => b.Meetings).HasForeignKey(c => c.MeetingTypeId); // FK_Meeting_MeetingType
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
