// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Calvary.Data
{
    // Meeting
    public partial class Meeting
    {
        public int Id { get; set; } // Id (Primary key)
        public int MeetingTypeId { get; set; } // MeetingTypeId
        public DateTime Date { get; set; } // Date
        public DateTime? FromTime { get; set; } // FromTime
        public DateTime? ToTime { get; set; } // ToTime
        public string Subject { get; set; } // Subject
        public int PengerjaPria { get; set; } // PengerjaPria
        public int PengerjaWanita { get; set; } // PengerjaWanita
        public int PenatuaPria { get; set; } // PenatuaPria
        public int PenatuaWanita { get; set; } // PenatuaWanita
        public int PartisipanPria { get; set; } // PartisipanPria
        public int PartisipanWanita { get; set; } // PartisipanWanita
        public DateTime CreatedWhen { get; set; } // CreatedWhen
        public string CreatedBy { get; set; } // CreatedBy
        public DateTime ChangedWhen { get; set; } // ChangedWhen
        public string ChangedWho { get; set; } // ChangedWho

        // Foreign keys
        public virtual MeetingType MeetingType { get; set; } // FK_Meeting_MeetingType
        
        public Meeting()
        {
            PengerjaPria = 0;
            PengerjaWanita = 0;
            PenatuaPria = 0;
            PenatuaWanita = 0;
            PartisipanPria = 0;
            PartisipanWanita = 0;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
