// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Calvary.Data
{
    // Member
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class Member
    {
        public int Id { get; set; } // Id (Primary key)
        public string MemberNo { get; set; } // MemberNo
        public string Name { get; set; } // Name
        public string NickName { get; set; } // NickName
        public string Gender { get; set; } // Gender
        public int? RegionId { get; set; } // RegionId
        public string BloodType { get; set; } // BloodType
        public string Rhesus { get; set; } // Rhesus
        public string MaritalStatus { get; set; } // MaritalStatus
        public DateTime? WhenFlagApa { get; set; } // WhenFlagAPA
        public DateTime? JoinDate { get; set; } // JoinDate
        public int? JoinFromShrineId { get; set; } // JoinFromShrineId
        public bool JoinFlagAtps { get; set; } // JoinFlagATPS
        public DateTime? ResignDate { get; set; } // ResignDate
        public int? ResignToShrineId { get; set; } // ResignToShrineId
        public int? ResignReasonId { get; set; } // ResignReasonId
        public string Address { get; set; } // Address
        public string City { get; set; } // City
        public string HomePhone { get; set; } // HomePhone
        public string CellPhone1 { get; set; } // CellPhone1
        public string CellPhone2 { get; set; } // CellPhone2
        public string Email { get; set; } // Email
        public DateTime? BirthDate { get; set; } // BirthDate
        public string BirthCity { get; set; } // BirthCity
        public string OfficeName { get; set; } // OfficeName
        public string OfficeAddress { get; set; } // OfficeAddress
        public string OfficePhone { get; set; } // OfficePhone
        public string OfficeCity { get; set; } // OfficeCity
        public string OfficeRole { get; set; } // OfficeRole
        public int? JobId { get; set; } // JobId
        public int? LastEducationGradeId { get; set; } // LastEducationGradeId
        public int? EducationMajorId { get; set; } // EducationMajorId
        public int? SkillId1 { get; set; } // SkillId1
        public int? SkillId2 { get; set; } // SkillId2
        public int? SkillId3 { get; set; } // SkillId3
        public int? HobbyId1 { get; set; } // HobbyId1
        public int? HobbyId2 { get; set; } // HobbyId2
        public int? HobbyId3 { get; set; } // HobbyId3
        public string ChrismationType { get; set; } // ChrismationType
        public int? BaptizedReasonId { get; set; } // BaptizedReasonId
        public int? ChrismationShrineId { get; set; } // ChrismationShrineId
        public string ChrismationPriest { get; set; } // ChrismationPriest
        public DateTime? ChrismationDate { get; set; } // ChrismationDate
        public string ChrismationCert { get; set; } // ChrismationCert
        public bool ChrismationFlagAtis { get; set; } // ChrismationFlagATIS
        public string SpouseName { get; set; } // SpouseName
        public string SpouseMemberNo { get; set; } // SpouseMemberNo
        public DateTime? MarriageDate { get; set; } // MarriageDate
        public string MarriageCert { get; set; } // MarriageCert
        public string MarriageCity { get; set; } // MarriageCity
        public int? MarriageShrineId { get; set; } // MarriageShrineId
        public string MarriagePriest { get; set; } // MarriagePriest
        public DateTime? MatrimonyDate { get; set; } // MatrimonyDate
        public string FatherName { get; set; } // FatherName
        public string FatherChrismationType { get; set; } // FatherChrismationType
        public string FatherMemberNo { get; set; } // FatherMemberNo
        public string MotherName { get; set; } // MotherName
        public string MotherChrismationType { get; set; } // MotherChrismationType
        public string MotherMemberNo { get; set; } // MotherMemberNo
        public int? EthnicId { get; set; } // EthnicId
        public string JoinNote { get; set; } // JoinNote
        public string ResignNote { get; set; } // ResignNote
        public int? ChildhoodBaptizedShrineId { get; set; } // ChildhoodBaptizedShrineId
        public string ChildhoodBaptizedPriest { get; set; } // ChildhoodBaptizedPriest
        public DateTime? ChildhoodBaptizedDate { get; set; } // ChildhoodBaptizedDate
        public string ChildhoodBaptizedCert { get; set; } // ChildhoodBaptizedCert
        public bool ChildhoodBaptizedFlagAtiot { get; set; } // ChildhoodBaptizedFlagATIOT
        public DateTime? DeceasedDate { get; set; } // DeceasedDate
        public string DeceasedNotes { get; set; } // DeceasedNotes
        public string Photo { get; set; } // Photo
        public DateTime CreatedWhen { get; set; } // CreatedWhen
        public string CreatedBy { get; set; } // CreatedBy
        public DateTime ChangedWhen { get; set; } // ChangedWhen
        public string ChangedBy { get; set; } // ChangedBy

        // Reverse navigation
        public virtual ICollection<MemberMarriage> MemberMarriages { get; set; } // MemberMarriage.FK_MemberMarriage_Member
        public virtual ICollection<MemberNote> MemberNotes { get; set; } // MemberNote.FK_MemberNotes_Member
        public virtual ICollection<MemberStateHistory> MemberStateHistories { get; set; } // MemberStateHistory.FK_MemberStatusHistory_Member
        public virtual ICollection<MemberVisit> MemberVisits { get; set; } // MemberVisit.FK_MemberVisit_Member
        public virtual ICollection<UserLogin> UserLogins { get; set; } // UserLogin.FK_UserLogin_Member

        // Foreign keys
        public virtual BaptizedReason BaptizedReason { get; set; } // FK_Member_BaptizedReason
        public virtual EducationGrade EducationGrade { get; set; } // FK_Member_LastEducationGrade
        public virtual EducationMajor EducationMajor { get; set; } // FK_Member_EducationMajor
        public virtual Ethnic Ethnic { get; set; } // FK_Member_Ethnic
        public virtual Hobby Hobby_HobbyId1 { get; set; } // FK_Member_Hobby
        public virtual Hobby Hobby_HobbyId2 { get; set; } // FK_Member_Hobby2
        public virtual Hobby Hobby_HobbyId3 { get; set; } // FK_Member_Hobby3
        public virtual Job Job { get; set; } // FK_Member_Job
        public virtual Region Region { get; set; } // FK_Member_Region
        public virtual ResignReason ResignReason { get; set; } // FK_Member_ResignReason
        public virtual Shrine Shrine_ChildhoodBaptizedShrineId { get; set; } // FK_Member_ChildhoodBaptizedShrine
        public virtual Shrine Shrine_ChrismationShrineId { get; set; } // FK_Member_ChrismationShrine
        public virtual Shrine Shrine_JoinFromShrineId { get; set; } // FK_Member_JoinFromShrine
        public virtual Shrine Shrine_ResignToShrineId { get; set; } // FK_Member_ResignToShrine
        public virtual Skill Skill_SkillId1 { get; set; } // FK_Member_Skill1
        public virtual Skill Skill_SkillId2 { get; set; } // FK_Member_Skill2
        public virtual Skill Skill_SkillId3 { get; set; } // FK_Member_Skill3
        
        public Member()
        {
            JoinFlagAtps = false;
            ChrismationFlagAtis = false;
            ChildhoodBaptizedFlagAtiot = false;
            MemberMarriages = new List<MemberMarriage>();
            MemberNotes = new List<MemberNote>();
            MemberStateHistories = new List<MemberStateHistory>();
            MemberVisits = new List<MemberVisit>();
            UserLogins = new List<UserLogin>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
