// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Calvary.Data
{
    // MemberMarriage
    public partial class MemberMarriage
    {
        public int Id { get; set; } // Id (Primary key)
        public int MemberId { get; set; } // MemberId
        public int? SpouseId { get; set; } // SpouseId
        public string SpouseName { get; set; } // SpouseName
        public DateTime? MarriageDate { get; set; } // MarriageDate
        public int? ShrineId { get; set; } // ShrineId
        public string Priest { get; set; } // Priest
        public string LegalRegNo { get; set; } // LegalRegNo
        public DateTime? LegalDate { get; set; } // LegalDate
        public string ChurchRegNo { get; set; } // ChurchRegNo
        public string City { get; set; } // City
        public DateTime CreatedWhen { get; set; } // CreatedWhen
        public string CreatedBy { get; set; } // CreatedBy
        public DateTime ChangedWhen { get; set; } // ChangedWhen
        public string ChangedBy { get; set; } // ChangedBy

        // Foreign keys
        public virtual Member Member { get; set; } // FK_MemberMarriage_Member
        public virtual Shrine Shrine { get; set; } // FK_MemberMarriage_Shrine
        
        public MemberMarriage()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
