// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Calvary.Data
{
    // Menu
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class Menu
    {
        public int Id { get; set; } // ID (Primary key)
        public string Title { get; set; } // Title
        public string NavigationTo { get; set; } // NavigationTo
        public int Seq { get; set; } // Seq
        public int? ParentMenuId { get; set; } // ParentMenuID
        public bool IsActive { get; set; } // IsActive
        public DateTime CreatedWhen { get; set; } // CreatedWhen
        public string CreatedWho { get; set; } // CreatedWho
        public DateTime ChangedWhen { get; set; } // ChangedWhen
        public string ChangedWho { get; set; } // ChangedWho

        // Reverse navigation
        public virtual ICollection<Menu> Menus { get; set; } // Menu.FK_Menu_ref_ParentMenu
        public virtual ICollection<RoleMenu> RoleMenus { get; set; } // Many to many mapping

        // Foreign keys
        public virtual Menu Menu_ParentMenuId { get; set; } // FK_Menu_ref_ParentMenu
        
        public Menu()
        {
            Seq = 0;
            IsActive = true;
            Menus = new List<Menu>();
            RoleMenus = new List<RoleMenu>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
