// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Calvary.Data
{
    // RoleMenu
    public partial class RoleMenuMapping : EntityTypeConfiguration<RoleMenu>
    {
        public RoleMenuMapping()
            : this("dbo")
        {
        }
 
        public RoleMenuMapping(string schema)
        {
            ToTable(schema + ".RoleMenu");
            HasKey(x => new { x.RoleId, x.MenuId });

            Property(x => x.RoleId).HasColumnName("RoleID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.MenuId).HasColumnName("MenuID").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
            Property(x => x.AllowAdd).HasColumnName("AllowAdd").IsRequired().HasColumnType("bit");
            Property(x => x.AllowEdit).HasColumnName("AllowEdit").IsRequired().HasColumnType("bit");
            Property(x => x.AllowDelete).HasColumnName("AllowDelete").IsRequired().HasColumnType("bit");

            // Foreign keys
            HasRequired(a => a.Menu).WithMany(b => b.RoleMenus).HasForeignKey(c => c.MenuId); // FK_RoleMenu_Menu
            HasRequired(a => a.Role).WithMany(b => b.RoleMenus).HasForeignKey(c => c.RoleId); // FK_RoleMenu_Role
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
