// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Calvary.Data
{
    // Schedule
    public partial class Schedule
    {
        public int Id { get; set; } // Id (Primary key)
        public string Title { get; set; } // Title
        public DateTime DateFrom { get; set; } // DateFrom
        public DateTime DateTo { get; set; } // DateTo
        public int ScheduleGroupId { get; set; } // ScheduleGroupId
        public string Notes { get; set; } // Notes
        public bool IsActive { get; set; } // IsActive
        public DateTime CreatedWhen { get; set; } // CreatedWhen
        public string CreatedBy { get; set; } // CreatedBy
        public DateTime ChangedWhen { get; set; } // ChangedWhen
        public string ChangedBy { get; set; } // ChangedBy
        public byte[] RowVersion { get; set; } // RowVersion

        // Foreign keys
        public virtual ScheduleGroup ScheduleGroup { get; set; } // FK_Schedule_ScheduleGroup
        
        public Schedule()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
