// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Calvary.Data
{
    // Skill
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class Skill
    {
        public int Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name
        public DateTime CreatedWhen { get; set; } // CreatedWhen
        public string CreatedBy { get; set; } // CreatedBy
        public DateTime ChangedWhen { get; set; } // ChangedWhen
        public string ChangedBy { get; set; } // ChangedBy

        // Reverse navigation
        public virtual ICollection<Member> Members_SkillId1 { get; set; } // Member.FK_Member_Skill1
        public virtual ICollection<Member> Members_SkillId2 { get; set; } // Member.FK_Member_Skill2
        public virtual ICollection<Member> Members_SkillId3 { get; set; } // Member.FK_Member_Skill3
        
        public Skill()
        {
            Members_SkillId1 = new List<Member>();
            Members_SkillId2 = new List<Member>();
            Members_SkillId3 = new List<Member>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
