// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Calvary.Data
{
    // UserLogin
    public partial class UserLogin
    {
        public int Id { get; set; } // Id (Primary key)
        public string UserName { get; set; } // UserName
        public string Password { get; set; } // Password
        public int RoleId { get; set; } // RoleId
        public DateTime? LastLogin { get; set; } // LastLogin
        public DateTime? LastChangePassword { get; set; } // LastChangePassword
        public int? MemberId { get; set; } // MemberId
        public bool IsSystemUser { get; set; } // IsSystemUser
        public bool IsActive { get; set; } // IsActive
        public DateTime CreatedWhen { get; set; } // CreatedWhen
        public string CreatedBy { get; set; } // CreatedBy
        public DateTime ChangedWhen { get; set; } // ChangedWhen
        public string ChangedBy { get; set; } // ChangedBy

        // Foreign keys
        public virtual Member Member { get; set; } // FK_UserLogin_Member
        public virtual Role Role { get; set; } // FK_UserLogin_Role
        
        public UserLogin()
        {
            IsSystemUser = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
