// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Calvary.Data
{
    // Worship
    public partial class WorshipMapping : EntityTypeConfiguration<Worship>
    {
        public WorshipMapping()
            : this("dbo")
        {
        }
 
        public WorshipMapping(string schema)
        {
            ToTable(schema + ".Worship");
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName("Id").IsRequired().HasColumnType("int").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
            Property(x => x.Date).HasColumnName("Date").IsRequired().HasColumnType("datetime");
            Property(x => x.WorshipTypeId).HasColumnName("WorshipTypeId").IsRequired().HasColumnType("int");
            Property(x => x.Subject).HasColumnName("Subject").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.Priest).HasColumnName("Priest").IsOptional().IsUnicode(false).HasColumnType("varchar").HasMaxLength(100);
            Property(x => x.JemaatPria).HasColumnName("JemaatPria").IsRequired().HasColumnType("int");
            Property(x => x.JemaatWanita).HasColumnName("JemaatWanita").IsRequired().HasColumnType("int");
            Property(x => x.SimpatisanPria).HasColumnName("SimpatisanPria").IsRequired().HasColumnType("int");
            Property(x => x.SimpatisanWanita).HasColumnName("SimpatisanWanita").IsRequired().HasColumnType("int");
            Property(x => x.PenatuaPria).HasColumnName("PenatuaPria").IsRequired().HasColumnType("int");
            Property(x => x.PenatuaWanita).HasColumnName("PenatuaWanita").IsRequired().HasColumnType("int");
            Property(x => x.AktivisPria).HasColumnName("AktivisPria").IsRequired().HasColumnType("int");
            Property(x => x.AktivisWanita).HasColumnName("AktivisWanita").IsRequired().HasColumnType("int");
            Property(x => x.PemusikPria).HasColumnName("PemusikPria").IsRequired().HasColumnType("int");
            Property(x => x.PemusikWanita).HasColumnName("PemusikWanita").IsRequired().HasColumnType("int");
            Property(x => x.Notes).HasColumnName("Notes").IsOptional().IsUnicode(false).HasColumnType("text").HasMaxLength(2147483647);
            Property(x => x.CreatedWhen).HasColumnName("CreatedWhen").IsRequired().HasColumnType("datetime");
            Property(x => x.CreatedBy).HasColumnName("CreatedBy").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);
            Property(x => x.ChangedWhen).HasColumnName("ChangedWhen").IsRequired().HasColumnType("datetime");
            Property(x => x.ChangedBy).HasColumnName("ChangedBy").IsRequired().IsUnicode(false).HasColumnType("varchar").HasMaxLength(50);

            // Foreign keys
            HasRequired(a => a.WorshipType).WithMany(b => b.Worships).HasForeignKey(c => c.WorshipTypeId); // FK_Workship_WorshipType
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
