// <auto-generated>
// ReSharper disable RedundantUsingDirective
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable RedundantNameQualifier
// TargetFrameworkVersion = 4.5
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.Entity.ModelConfiguration;
using System.Threading;
using DatabaseGeneratedOption = System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption;

namespace Calvary.Data
{
    // Worship
    [GeneratedCodeAttribute("EF.Reverse.POCO.Generator", "2.17.1.0")]
    public partial class Worship
    {
        public int Id { get; set; } // Id (Primary key)
        public DateTime Date { get; set; } // Date
        public int WorshipTypeId { get; set; } // WorshipTypeId
        public string Subject { get; set; } // Subject
        public string Priest { get; set; } // Priest
        public int JemaatPria { get; set; } // JemaatPria
        public int JemaatWanita { get; set; } // JemaatWanita
        public int SimpatisanPria { get; set; } // SimpatisanPria
        public int SimpatisanWanita { get; set; } // SimpatisanWanita
        public int PenatuaPria { get; set; } // PenatuaPria
        public int PenatuaWanita { get; set; } // PenatuaWanita
        public int AktivisPria { get; set; } // AktivisPria
        public int AktivisWanita { get; set; } // AktivisWanita
        public int PemusikPria { get; set; } // PemusikPria
        public int PemusikWanita { get; set; } // PemusikWanita
        public string Notes { get; set; } // Notes
        public DateTime CreatedWhen { get; set; } // CreatedWhen
        public string CreatedBy { get; set; } // CreatedBy
        public DateTime ChangedWhen { get; set; } // ChangedWhen
        public string ChangedBy { get; set; } // ChangedBy

        // Reverse navigation
        public virtual ICollection<Income> Incomes { get; set; } // Income.FK_Income_Worship

        // Foreign keys
        public virtual WorshipType WorshipType { get; set; } // FK_Workship_WorshipType
        
        public Worship()
        {
            JemaatPria = 0;
            JemaatWanita = 0;
            SimpatisanPria = 0;
            SimpatisanWanita = 0;
            PenatuaPria = 0;
            PenatuaWanita = 0;
            AktivisPria = 0;
            AktivisWanita = 0;
            PemusikPria = 0;
            PemusikWanita = 0;
            Incomes = new List<Income>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
